// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  micro_kernel

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( DemoCollector ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DemoCollector ) UnmarshalJSON([]byte) error { return nil }
func ( DemoCollector ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DemoCollector ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DemoCollector *DemoCollector
